'use client';

/**
 * Home Page with React Flow Diagram
 * Generated by Roo
 */
import dynamic from "next/dynamic";
import CurrentSystem from "@/components/CurrentSystem";
import {useState} from "react";

// Use dynamic import for the FlowDiagram component
const FlowDiagram = dynamic(
  () => import('@/components/FlowDiagram'),
  { ssr: false }
);

export default function Home() {

    const [currentSystemId, setCurrentSystemId] = useState<number | null>(null)

  return (
    <div className="container mx-auto p-4">
      <h1 className="text-2xl font-bold mb-4">Next.js + Supabase + React Flow</h1>
      <div className="border rounded-lg overflow-hidden">
          <div style={{ width: '60%', float: 'left' }}>
              <FlowDiagram
                  currentSystemId={currentSystemId}
                  onSystemChange={(newId: number | null) => setCurrentSystemId(newId)}
              />
          </div>
          <div style={{ width: '40%', height: '800px', float: 'right', backgroundColor: '#f5f5f5' }}>
              {currentSystemId && <CurrentSystem
                  currentSystemId={currentSystemId}
                  onSystemChange={(newId: number | null) => setCurrentSystemId(newId)}
              />}

              {!currentSystemId && <div
                  className="flex items-center m-9 mt-20 top-40 p-4 mb-4 text-sm text-yellow-800 border border-yellow-300 rounded-lg bg-yellow-50 dark:bg-gray-800 dark:text-yellow-300 dark:border-yellow-800"
                  role="alert">
                  <svg className="shrink-0 inline w-4 h-4 me-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                       fill="currentColor" viewBox="0 0 20 20">
                      <path
                          d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
                  </svg>
                  <span className="sr-only">Info</span>
                  <div className="text-xl">
                      <span className="font-medium">No system selected!</span>
                  </div>
              </div>}
          </div>
      </div>
    </div>
  );
}
