'use client';

/**
 * Home Page with React Flow Diagram
 * Generated by Roo
 */
import dynamic from "next/dynamic";
import CurrentSystem from "@/components/CurrentSystem";

// Use dynamic import for the FlowDiagram component
const FlowDiagram = dynamic(
  () => import('@/components/FlowDiagram'),
  { ssr: false }
);

export default function Home() {
  return (
    <div className="container mx-auto p-4">
      <h1 className="text-2xl font-bold mb-4">Next.js + Supabase + React Flow</h1>
      <div className="border rounded-lg overflow-hidden">
          <div style={{ width: '60%', height: '100%', float: 'left' }}>
              <FlowDiagram />
          </div>
          <div style={{ width: '39%', height: '50%', float: 'right', backgroundColor: '#f5f5f5' }}>
              <CurrentSystem />
          </div>
      </div>
    </div>
  );
}
